module t510_fengine_stub_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        pps_in,
    input  wire        ref_lock_in,
    input  wire        rfdc_ready_in,
    input  wire [31:0] s_axi_awaddr,
    input  wire        s_axi_awvalid,
    output wire        s_axi_awready,
    input  wire [31:0] s_axi_wdata,
    input  wire [3:0]  s_axi_wstrb,
    input  wire        s_axi_wvalid,
    output wire        s_axi_wready,
    output wire [1:0]  s_axi_bresp,
    output wire        s_axi_bvalid,
    input  wire        s_axi_bready,
    input  wire [31:0] s_axi_araddr,
    input  wire        s_axi_arvalid,
    output wire        s_axi_arready,
    output wire [31:0] s_axi_rdata,
    output wire [1:0]  s_axi_rresp,
    output wire        s_axi_rvalid,
    input  wire        s_axi_rready,
    output wire        irq
);

    wire [63:0] unused_tx_tdata;
    wire [7:0]  unused_tx_tkeep;
    wire        unused_tx_tvalid;
    wire        unused_tx_tlast;

    t510_fengine_top u_core (
        .clk(clk),
        .rst_n(rst_n),
        .ctrl_clk(clk),
        .ctrl_rst_n(rst_n),
        .pps_in(pps_in),
        .ref_lock_in(ref_lock_in),
        .rfdc_ready_in(rfdc_ready_in),
        .s_axi_awaddr(s_axi_awaddr),
        .s_axi_awvalid(s_axi_awvalid),
        .s_axi_awready(s_axi_awready),
        .s_axi_wdata(s_axi_wdata),
        .s_axi_wstrb(s_axi_wstrb),
        .s_axi_wvalid(s_axi_wvalid),
        .s_axi_wready(s_axi_wready),
        .s_axi_bresp(s_axi_bresp),
        .s_axi_bvalid(s_axi_bvalid),
        .s_axi_bready(s_axi_bready),
        .s_axi_araddr(s_axi_araddr),
        .s_axi_arvalid(s_axi_arvalid),
        .s_axi_arready(s_axi_arready),
        .s_axi_rdata(s_axi_rdata),
        .s_axi_rresp(s_axi_rresp),
        .s_axi_rvalid(s_axi_rvalid),
        .s_axi_rready(s_axi_rready),
        .s_axis_adc_tdata(1024'd0),
        .s_axis_adc_tuser(32'd0),
        .s_axis_adc_sample0(64'd0),
        .s_axis_adc_tvalid(1'b0),
        .s_axis_adc_tlast(1'b0),
        .s_axis_adc_tready(),
        .s_axis_preview_tdata0(256'd0),
        .s_axis_preview_tdata1(256'd0),
        .s_axis_preview_tdata2(256'd0),
        .s_axis_preview_tdata3(256'd0),
        .s_axis_preview_sample0(64'd0),
        .s_axis_preview_tvalid(1'b0),
        .s_axis_raw_witness_tdata0(256'd0),
        .s_axis_raw_witness_tdata1(256'd0),
        .s_axis_raw_witness_tdata2(256'd0),
        .s_axis_raw_witness_tdata3(256'd0),
        .s_axis_raw_witness_sample0(64'd0),
        .s_axis_raw_witness_tvalid(1'b0),
        .rfdc_status_flags(32'd0),
        .rfdc_sample_count(64'd0),
        .rfdc_dropped_count(32'd0),
        .rfdc_current_valid_mask(16'd0),
        .rfdc_seen_valid_mask(16'd0),
        .dac_audit_phase_epoch_seen(32'd0),
        .dac_audit_ch0_phase_acc(32'd0),
        .dac_audit_ch0_phase_step(32'd0),
        .dac_audit_ch0_phase0(32'd0),
        .dac_audit_ch0_mode(32'd0),
        .dac_tx_witness_armed(1'b0),
        .dac_tx_witness_valid(1'b0),
        .dac_tx_witness_capturing(1'b0),
        .dac_tx_witness_overflow(1'b0),
        .dac_tx_witness_tvalid_seen(1'b0),
        .dac_tx_witness_tready_seen(1'b0),
        .dac_tx_witness_ready_gap_seen(1'b0),
        .dac_tx_witness_word_count(9'd0),
        .dac_tx_witness_phase_epoch(32'd0),
        .dac_tx_witness_phase_acc(32'd0),
        .dac_tx_witness_phase_step(32'd0),
        .dac_tx_witness_phase0(32'd0),
        .dac_tx_witness_mode(32'd0),
        .dac_tx_witness_ready_gap_count(32'd0),
        .dac_tx_witness_rd_data(32'd0),
        .rfdc_active_port_mask(),
        .m_axis_tx_tdata(unused_tx_tdata),
        .m_axis_tx_tkeep(unused_tx_tkeep),
        .m_axis_tx_tvalid(unused_tx_tvalid),
        .m_axis_tx_tlast(unused_tx_tlast),
        .m_axis_tx_tready(1'b1),
        .cmac_tx_clk(clk),
        .cmac_tx_rst_n(rst_n),
        .cmac_tx_axis_tdata(),
        .cmac_tx_axis_tkeep(),
        .cmac_tx_axis_tvalid(),
        .cmac_tx_axis_tlast(),
        .cmac_tx_axis_tready(1'b1),
        .tx_link_status_flags(32'h0000_101d),
        .tx_dry_run_packet_count(32'd0),
        .tx_dry_run_byte_count(32'd0),
        .dac_tone_enable(),
        .dac_tone_amplitude(),
        .dac_tone_phase_step(),
        .dac_enable_mask(),
        .dac_tone_amplitude_vec(),
        .dac_tone_phase_step_vec(),
        .dac_tone_phase0_vec(),
        .dac_tone_phase_inject_vec(),
        .dac_tone_mode_vec(),
        .dac_phase_epoch(),
        .dac_tx_witness_arm_pulse(),
        .dac_tx_witness_clear_pulse(),
        .dac_tx_witness_capture_words(),
        .dac_tx_witness_rd_word(),
        .irq(irq)
    );

endmodule
