'use strict';
const el=id=>document.getElementById(id),cache=new Map(),hidden=new Set(),names={natural:'自然',A1:'A1',B:'B',A2:'A2',released:'解除覆盖'},colors={natural:'#888888',A1:'#1769aa',B:'#d37423',A2:'#9d469d',released:'#258e7f'};let meta,generation=0;
const ids=['amp','phase','iq','complex','power','spectrum'];const fmt=x=>Number(x).toLocaleString('zh-CN',{maximumFractionDigits:5});
function weighted(d,start,end,key){let a=0,n=0;for(let i=start;i<end;i++){a+=d[key][i]*d.n_valid[i];n+=d.n_valid[i];}return a/n;}
async function render(){const token=++generation;window.ocbReady=false;try{
 const pair=el('pair').value,k=el('bin').value,policy=el('policy').value,start=el('window').value==='test'?600:0,selected=[...document.querySelectorAll('#states input:checked')].map(x=>x.value);
 if(!cache.has(pair)){const r=await fetch(`/static/ocb2-data/pairs/${pair}.json`);if(!r.ok)throw Error('读取失败');cache.set(pair,await r.json());}const all=cache.get(pair);if(token!==generation)return;
 const traces=Object.fromEntries(ids.map(id=>[id,[]]));
 for(const s of selected){const d=all.native[k][s],bg=policy==='raw'?[0,0]:d[policy],base={name:names[s],legendgroup:s,visible:hidden.has(s)?'legendonly':true,type:'scattergl',mode:'markers',marker:{color:colors[s],size:3,opacity:.65}},re=d.real.slice(start).map(v=>v-bg[0]),im=d.imag.slice(start).map(v=>v-bg[1]),x=re.map((_,i)=>(i+start+.5)/10);
 traces.amp.push({...base,x,y:re.map((v,i)=>Math.hypot(v,im[i]))});traces.phase.push({...base,x,y:re.map((v,i)=>v===0&&im[i]===0?null:Math.atan2(im[i],v)*180/Math.PI)});
 const offset=start/100,tx=d.ten_real.slice(offset).map((_,i)=>(i+offset)*10+5),tr=d.ten_real.slice(offset).map(v=>v-bg[0]),ti=d.ten_imag.slice(offset).map(v=>v-bg[1]),line={...base,type:'scatter',mode:'lines+markers',line:{color:colors[s]},marker:{color:colors[s],size:6}};
 traces.iq.push({...line,name:names[s]+' Re',x:tx,y:tr},{...line,name:names[s]+' Im',showlegend:false,x:tx,y:ti,line:{color:colors[s],dash:'dash'}});
 traces.complex.push({...line,x:tr,y:ti,text:tx.map(t=>`${t}s`),hovertemplate:'Re %{x:.5f}<br>Im %{y:.5f}<br>%{text}<extra>%{fullData.name}</extra>'});
 for(const [axis,key] of [['a','power_a'],['b','power_b']])traces.power.push({...line,name:names[s]+' ADC'+pair.split('-')[axis==='a'?0:1],showlegend:axis==='a',x:tx,y:tx.map(t=>weighted(d,(t-5)*10,(t+5)*10,key)),line:{color:colors[s],dash:axis==='a'?'solid':'dash'}});
 const y=policy==='raw'?all.spectra.raw_rho[s]:all.spectra.corrected_rho[policy][s];traces.spectrum.push({...line,type:'scattergl',mode:'lines',x:y.map((_,i)=>i),y});
 }
 const base={margin:{l:85,r:20,t:90,b:65},legend:{orientation:'h',y:1.03,yanchor:'bottom'},font:{family:'system-ui',size:13}},config={responsive:true,displayModeBar:false},timeAxis={title:{text:'相对本段起点（秒）'},range:[start/10,120]},bandAxis={title:{text:'global bin（3072–3328 对应120–140 MHz）'},range:el('band').value==='science'?[3072,3328]:[0,4095]};
 const layouts={amp:{xaxis:timeAxis,yaxis:{title:{text:'幅度（count²）'},rangemode:'tozero'}},phase:{xaxis:timeAxis,yaxis:{title:{text:'相位（度）'},range:[-180,180]}},iq:{xaxis:timeAxis,yaxis:{title:{text:'实部／虚部（count²）'}}},complex:{xaxis:{title:{text:'实部（count²）'}},yaxis:{title:{text:'虚部（count²）'},scaleanchor:'x',scaleratio:1}},power:{xaxis:timeAxis,yaxis:{title:{text:'自功率（count²）'}}},spectrum:{xaxis:bandAxis,yaxis:{title:{text:'归一化幅度（%）'}}}};
 await Promise.all(ids.map(id=>Plotly.react(id,traces[id],{...base,...layouts[id]},config)));
 const metrics=['B_vs_interpolated_A','A_return','within_10s_change'];await Plotly.react('contrast',metrics.map((key,i)=>({type:'scattergl',mode:'lines',name:['B偏离插值A','A返回差','段内10秒变化'][i],x:all.spectra[key].map((_,j)=>j),y:all.spectra[key],line:{color:['#c0641e','#1769aa','#808080'][i]}})),{...base,xaxis:bandAxis,yaxis:{title:{text:'归一化复差（%）'}}},config);
 el('policyTable').innerHTML=meta.states.map(s=>{const d=all.native[k][s],re=weighted(d,600,1200,'real'),im=weighted(d,600,1200,'imag');return `<tr><td>${names[s]}</td>${[[0,0],d.fixed,d.local].map(b=>`<td>${fmt(Math.hypot(re-b[0],im-b[1]))}</td>`).join('')}<td>${fmt(Math.atan2(im,re)*180/Math.PI)}</td></tr>`;}).join('');
 el('status').textContent=`ADC${pair.replace('-','–ADC')} · bin${k} · ${policy} · 每段${1200-start}个原生100 ms点`;window.ocbReady=true;
 }catch(e){el('status').textContent='加载失败：'+e.message;console.error(e);}}
async function start(){meta=await(await fetch('/static/ocb2-data/summary.json')).json();el('pair').innerHTML=meta.pairs.map(p=>`<option value="${p.join('-')}">ADC${p.join('–ADC')}</option>`).join('');el('pair').value='6-7';el('bin').innerHTML=meta.bins.map(k=>`<option value="${k}">${(200+(k-4096)*320/4096).toFixed(6)} MHz · ${k}</option>`).join('');el('bin').value='3073';el('allTable').innerHTML=meta.summary.map(r=>`<tr><td><button data-pair="${r.pair.join('-')}">${r.pair.join('–')}</button></td><td>${r.target_pair?'目标相关':'对照'}</td>${['B_vs_interpolated_A','A_return','within_10s_change','same_value_change','release_change'].map(k=>`<td>${fmt(r[k])}</td>`).join('')}</tr>`).join('');el('identity').textContent=JSON.stringify({alpha:meta.alpha,sources:meta.sources,queue_manifest_sha256:meta.queue_manifest_sha256,limitations:meta.limitations},null,2);await render();for(const id of ['pair','bin','policy','window','band'])el(id).onchange=render;document.querySelectorAll('#states input').forEach(e=>e.onchange=render);el('showAll').onclick=()=>{hidden.clear();render();};el('allTable').onclick=e=>{if(e.target.dataset.pair){el('pair').value=e.target.dataset.pair;render();el('status').scrollIntoView();}};for(const id of ids){el(id).on('plotly_legendclick',e=>{const k=e.data[e.curveNumber].legendgroup;hidden.has(k)?hidden.delete(k):hidden.add(k);render();return false;});el(id).on('plotly_legenddoubleclick',e=>{const k=e.data[e.curveNumber].legendgroup;hidden.clear();e.data.forEach(t=>{if(t.legendgroup!==k)hidden.add(t.legendgroup);});render();return false;});}}
start().catch(e=>el('status').textContent='加载失败：'+e.message);
